### ISSUE TITLE
not working on remote files

### ISSUE THREAD

**Issue by testcaseone** [d9705996/perl-toolbox#1]
I use SSH FS to work on files using ssh. Syntax Checking and Linting isn't working in that combination, probably because the file path is used. 
A workaround would be great, like saving a local copy in that case so Syntax Checking and Linting can be used.

**Comment by d9705996** [comment]
@testcaseone - I do not have the ability to replicate your issue with sshfs.  

My workflow is to use an [this](https://marketplace.visualstudio.com/items?itemName=liximomo.sftp) SFTP extension which syncs the local/remote change using SFTP/SSH and allow linting on the local copy?  

Would this be an adequate workaround to your problem.

**Comment by testcaseone** [comment]
SFTP sadly doesn't work in my case and it looks like that extension doesn't use SSH only. Also the directory i work with is rather big, so a tool that syncs all files in the folder would be bad too.

Thanks anyways, this extension is still great.

**Comment by d9705996** [comment]
@testcaseone - can you give some details of both your host OS and the system your connecting to. I'll see if I can replicate

**Comment by testcaseone** [comment]
sure. my host is a windows 10 machine, i connect to a virtualbox vm that runs centos7. 
i connect to the vm with the vscode extensions SSH FS.
if i saw that right in your code, you forward the path to the file for linting and syntax highlighting. In my case that would not be a locally reachable path.

**Comment by d9705996** [comment]
@testcaseone - I have setup and tested with SSHFS and you are correct that the issue is with the file system path as `this.document.fileName` for SSHFS files is just returning the filename. e.g. \test.pl   

I think putting the file contents into a temporary file and linting this should work.

**Comment by d9705996** [comment]
@testcaseone - I have released v1.2.0 of the extension and is live on market place.  This shoudl resolve the SSH FS issue.  Any further problems please open a new issue

**Comment by testcaseone** [comment]
Thank you, great work!
