### ISSUE TITLE
General usage

### ISSUE THREAD

**Issue by PaulGWebster** [d9705996/perl-toolbox#12]
Good day I have added the correct paths to settings.json

    "perl-toolbox.syntax.path": "C:\\perl\\perl\\bin",
    "perl-toolbox.lint.path": "C:\\perl\\perl\\site\\bin"

but yet I do not seem to get any linting or syntax highlighting, I have cpan installed perlcritic also:

`C:\Users\paulg>c:\perl\perl\site\bin\perlcritic --version
1.132`

`C:\Users\paulg>c:\perl\perl\bin\perl.exe -v

This is perl 5, version 28, subversion 1 (v5.28.1) built for MSWin32-x64-multi-thread

Copyright 1987-2018, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.`

I have even gone into view->debug and no errors are being raised, how do you get this module to do something? (this filetype is showing up as perl in the editor *.pm type)

**Comment by PaulGWebster** [comment]
I also just tried setting: perl-toolbox.syntax.enabled to true via settings.json which also appears to have made no difference

**Comment by d9705996** [comment]
@PaulGWebster - What version of VSCode are you using?  I have noticed that the extension is no longer working for me since upgrading to v1.32

I can see errors in Developer Tools  when trying to lint Perl files

```
  ERR Callback must be a function: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at PerlLintProvider.lint (C:\Users\dwalker\.vscode\extensions\d9705996.perl-toolbox-1.3.0\out\features\PerlLintProvider.js:40:12)
```

I need to review and imp,implement a fix

**Comment by PaulGWebster** [comment]
Good Day @d9705996

I am running 1.32.3 (screenshot attached) but get no debug log of any kind anywhere [OneDrive](https://1drv.ms/u/s!AkvwG6Qrk79x7CUT4_AmKhLEE7up)

**Comment by PaulGWebster** [comment]
Just for completeness here is screenshots of the other sections relevant to vscode as well: [OneDrive](https://1drv.ms/f/s!AkvwG6Qrk79x7Cl1I4KaB0Gk06ES)

**Comment by marlencrabapple** [comment]
> Good Day @d9705996
> 
> I am running 1.32.3 (screenshot attached) but get no debug log of any kind anywhere [OneDrive](https://1drv.ms/u/s!AkvwG6Qrk79x7CUT4_AmKhLEE7up)

@PaulGWebster The information he posted is found in the developer tools console (ctrl+shift+i on my machine).

@d9705996 I'm seeing the same thing:

```
workbench.main.js:179771 [[object Object]]Callback must be a function
$onExtensionRuntimeError @ workbench.main.js:179771
_doInvokeHandler @ workbench.main.js:178351
_invokeHandler @ workbench.main.js:178336
_receiveRequest @ workbench.main.js:178268
_receiveOneMessage @ workbench.main.js:178199
RPCProtocol._protocol.onMessage @ workbench.main.js:178089
fire @ workbench.main.js:5657
deliverMessages @ workbench.main.js:24483
source @ workbench.main.js:24489
fire @ workbench.main.js:5657
acceptChunk @ workbench.main.js:24337
Protocol._socketDataListener @ workbench.main.js:24363
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:179772 TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
	at maybeCallback (fs.js:157)
	at Object.fs.writeFile (fs.js:1290)
	at PerlLintProvider.lint (/home/taargus/.vscode/extensions/d9705996.perl-toolbox-1.3.0/out/features/PerlLintProvider.js:40)
...
```

**Comment by d9705996** [comment]
@marlencrabapple - I'm struggling to get any time to look at this right now. I'm open to PRs if you want to try fixing this

**Comment by PaulGWebster** [comment]
any other information I could provide to help out?

**Comment by d9705996** [comment]
v1.3.1 has been released of the extension (Thanks @seagirl) that should fix the callback errors

Please update and retest and advise if you are still having issues

**Comment by d9705996** [comment]
@PaulGWebster , I'm going to close this down as the bug fixes in the latest version should fix your issue.  If  not let me know.

**Comment by PaulGWebster** [comment]
I hope this does not re-open it but yep working great now :)
