### ISSUE TITLE
How to add a sourcecode path to @INC?

### ISSUE THREAD

**Issue by Skeeve** [d9705996/perl-toolbox#15]
I konw that you can set

`"perl-toolbox.syntax.includePaths":["/path/to/my/project/lib"],`

but how can I make this Project-specific?

**Comment by d9705996** [comment]
In VSCode you can setup [workspace settings](https://code.visualstudio.com/docs/getstarted/settings) on a project by project basis.

This should allow you to set the `@INC` path on a per project basis as

> Workspace settings override user settings.

**Comment by Skeeve** [comment]
Thanks for teaching me visual studio code, @d9705996. I really did not know that.
