### ISSUE TITLE
No Per Project .perlcriticrc

### ISSUE THREAD

**Issue by chrisbanm** [d9705996/perl-toolbox#17]
So I see where you can set the flag to use .perlcriticrc and even the ability to set the absolute path to .perlcriticrc but I want each project in VSC to have it's own project specific .perlcriticrc in the project's home directory. This isn't really related to issue #14 since I'd like a way to specify the RELATIVE path to .perlcriticrc (i.e. at the project root directory). If I have to set absolute paths then using .perlcriticrc fails as soon as this project is moved/copied/cloned to a different directory than the original project.

**Comment by d9705996** [comment]
https://github.com/d9705996/perl-toolbox/pull/16 should add this feature.

**Comment by d9705996** [comment]
should now be added in v.1.4.0 - see https://github.com/d9705996/perl-toolbox#placeholder-workspaceroot
