### ISSUE TITLE
weird behaviour on vs code

### ISSUE THREAD

**Issue by laama1** [d9705996/perl-toolbox#3]
What does this mean? "it used to work before"
perlcritic version: 1.130, perl version: 5.26.2.
I have no such directory. Why is there "/tmp" in front of the path? How to solve this?
I have set "perl-toolbox.syntax.path": "/usr/bin/", "perl-toolbox.lint.path": "/usr/bin/",
Running Fedora 28 latest updates, vs code 1.25.0 x64

> renderer1] [error] ENOENT: no such file or directory, open '/tmp/home/mini/Mount/kiva/scripts/irssi-scripts/urltitle3.pl.lint': Error: ENOENT: no such file or directory, open '/tmp/home/mini/Mount/kiva/scripts/irssi-scripts/urltitle3.pl.lint'

**Comment by d9705996** [comment]
Related to aef25e7ebb0001c5df91b8fbbd234fea9b44ca47 using fs.basename instead of the fullpath should fix this. I will release a patch in the next 24 hours

**Comment by d9705996** [comment]
@laama1 - Thank you for raising the above bug.  A patch has been released to Marketplace which will; resolve the issue.
