### ISSUE TITLE
wrong highlighting of code

### ISSUE THREAD

**Issue by duartemolha** [d9705996/perl-toolbox#8]
Hi 
I am enjoying coding in my favorite language in VS code, but I noticed a bug on the highlighing of a block of code and I wonder if this is caused by this package or from some other package I have installed 

https://github.com/login?return_to=%2Fd9705996%2Fperl-toolbox%2Fissues%2Fnew
![image](https://user-images.githubusercontent.com/722005/45955231-3f0e3580-c007-11e8-8ee9-a949a7b499b8.png)

As you can see the split on an escaped pipe breaks the highlighting.

Thanks

Duarte

**Comment by d9705996** [comment]
@duartemolha - this should not be related to the plugin as it only adds diagnostics to the active document (The squiggly lines).  If you disable to plugin do you still get the same behaviour?

**Comment by duartemolha** [comment]
Thanks. I wasn't sure what was providing the code highlighting. But based
on your answer it cannot be your plugin
